from typing import Literal, NotRequired, TypedDict


class HorizonsParams(TypedDict):
    """Parameters for the Horizons API"""

    # Common Parameters
    format: NotRequired[Literal["json", "text"]]  # json
    COMMAND: NotRequired[str]  # none
    OBJ_DATA: NotRequired[Literal["'NO'", "'YES'"]]  # YES
    MAKE_EPHEM: NotRequired[Literal["'NO'", "'YES'"]]  # YES
    EPHEM_TYPE: NotRequired[
        Literal["'OBSERVER'", "'VECTORS'", "'ELEMENTS'", "'SPK'", "'APPROACH'"]
    ]  # OBSERVER
    EMAIL_ADDR: NotRequired[str]  # none
    # Ephemeris-Specific Parameters
    CENTER: NotRequired[str]  # Geocentric
    REF_PLANE: NotRequired[
        Literal["'ECLIPTIC'", "'FRAME'", "'BODY EQUATOR'"]
    ]  # ECLIPTIC
    COORD_TYPE: NotRequired[Literal["'GEODETIC'", "'CYLINDRICAL'"]]  # GEODETIC
    SITE_COORD: NotRequired[str]  # '0,0,0'
    START_TIME: NotRequired[str]  # none
    STOP_TIME: NotRequired[str]  # none
    STEP_SIZE: NotRequired[str]  # '60 min'
    TIME_DIGITS: NotRequired[Literal["'MINUTES'", "'SECONDS'", "'FRACSEC'"]]  # MINUTES
    TIME_TYPE: NotRequired[Literal["'UT'", "'TT'", "'TDB'"]]  # varies with EPHEM_TYPE
    TIME_ZONE: NotRequired[str]  # '+00:00'
    TLIST: NotRequired[str]  # none
    TLIST_TYPE: NotRequired[Literal["'JD'", "'MJD'", "'CAL'"]]  # none
    QUANTITIES: NotRequired[Literal["'A'"]]  # 'A'
    REF_SYSTEM: NotRequired[Literal["'ICRF'", "'B1950'"]]  # ICRF
    OUT_UNITS: NotRequired[Literal["'KM-S'", "'AU-D'", "'KM-D'"]]  # KM-S
    VEC_TABLE: NotRequired[
        Literal[
            "'1'",
            "'1x'",
            "'1xa'",
            "'1xar'",
            "'1xarp'",
            "'2'",
            "'2x'",
            "'2xa'",
            "'2xar'",
            "'2xarp'",
            "'3'",
            "'4'",
            "'5'",
            "'6'",
        ]
    ]  # 3
    VEC_CORR: NotRequired[Literal["'NONE'", "'LT'", "'LT+S'"]]  # NONE
    CAL_FORMAT: NotRequired[Literal["'CAL'", "'JD'", "'BOTH'"]]  # CAL
    CAL_TYPE: NotRequired[Literal["'MIXED'", "'GREGORIAN'"]]  # MIXED
    ANG_FORMAT: NotRequired[Literal["'HMS'", "'DEG'"]]  # HMS
    APPARENT: NotRequired[Literal["'AIRLESS'", "'REFRACTED'"]]  # AIRLESS
    RANGE_UNITS: NotRequired[Literal["'AU'", "'KM'"]]  # AU
    # ... TODO
    CSV_FORMAT: NotRequired[Literal["'NO'", "'YES'"]]  # NO
    VEC_LABELS: NotRequired[Literal["'NO'", "'YES'"]]  # YES
    VEC_DELTA_T: NotRequired[Literal["'NO'", "'YES'"]]  # NO
    # ... TODO


Body = Literal[
    "Solar System Barycenter",
    "Mercury Barycenter",
    "Venus Barycenter",
    "Earth-Moon Barycenter",
    "Mars Barycenter",
    "Jupiter Barycenter",
    "Saturn Barycenter",
    "Uranus Barycenter",
    "Neptune Barycenter",
    "Pluto Barycenter",
    "Sun",
    "SEMB-L1",
    "SEMB-L2",
    "SEMB-L4",
    "SEMB-L5",
    "Mercury",
    "Venus",
    "Moon",
    "Earth",
    "Phobos",
    "Deimos",
    "Mars",
    "Io",
    "Europa",
    "Ganymede",
    "Callisto",
    "Amalthea",
    "Himalia",
    "Elara",
    "Pasiphae",
    "Sinope",
    "Lysithea",
    "Carme",
    "Ananke",
    "Leda",
    "Thebe",
    "Adrastea",
    "Metis",
    "Callirrhoe",
    "Themisto",
    "Megaclite",
    "Taygete",
    "Chaldene",
    "Harpalyke",
    "Kalyke",
    "Iocaste",
    "Erinome",
    "Isonoe",
    "Praxidike",
    "Autonoe",
    "Thyone",
    "Hermippe",
    "Aitne",
    "Eurydome",
    "Euanthe",
    "Euporie",
    "Orthosie",
    "Sponde",
    "Kale",
    "Pasithee",
    "Hegemone",
    "Mneme",
    "Aoede",
    "Thelxinoe",
    "Arche",
    "Kallichore",
    "Helike",
    "Carpo",
    "Eukelade",
    "Cyllene",
    "Kore",
    "Herse",
    "",
    "Dia",
    "Eirene",
    "Philophrosyne",
    "Eupheme",
    "Valetudo",
    "Pandia",
    "Ersa",
    "Jupiter",
    "Mimas",
    "Enceladus",
    "Tethys",
    "Dione",
    "Rhea",
    "Titan",
    "Hyperion",
    "Iapetus",
    "Phoebe",
    "Janus",
    "Epimetheus",
    "Helene",
    "Telesto",
    "Calypso",
    "Atlas",
    "Prometheus",
    "Pandora",
    "Pan",
    "Ymir",
    "Paaliaq",
    "Tarvos",
    "Ijiraq",
    "Suttungr",
    "Kiviuq",
    "Mundilfari",
    "Albiorix",
    "Skathi",
    "Erriapus",
    "Siarnaq",
    "Thrymr",
    "Narvi",
    "Methone",
    "Pallene",
    "Polydeuces",
    "Daphnis",
    "Aegir",
    "Bebhionn",
    "Bergelmir",
    "Bestla",
    "Farbauti",
    "Fenrir",
    "Fornjot",
    "Hati",
    "Hyrrokkin",
    "Kari",
    "Loge",
    "Skoll",
    "Surtur",
    "Anthe",
    "Jarnsaxa",
    "Greip",
    "Tarqeq",
    "Aegaeon",
    "Gridr",
    "Angrboda",
    "Skrymir",
    "Gerd",
    "Eggther",
    "Beli",
    "Gunnlod",
    "Thiazzi",
    "Alvaldi",
    "Geirrod",
    "Saturn",
    "Ariel",
    "Umbriel",
    "Titania",
    "Oberon",
    "Miranda",
    "Cordelia",
    "Ophelia",
    "Bianca",
    "Cressida",
    "Desdemona",
    "Juliet",
    "Portia",
    "Rosalind",
    "Belinda",
    "Puck",
    "Caliban",
    "Sycorax",
    "Prospero",
    "Setebos",
    "Stephano",
    "Trinculo",
    "Francisco",
    "Margaret",
    "Ferdinand",
    "Perdita",
    "Mab",
    "Cupid",
    "Uranus",
    "2023U1",
    "Triton",
    "Nereid",
    "Naiad",
    "Thalassa",
    "Despina",
    "Galatea",
    "Larissa",
    "Proteus",
    "Halimede",
    "Psamathe",
    "Sao",
    "Laomedeia",
    "Neso",
    "Hippocamp",
    "Neptune",
    "2002N5",
    "2021N1",
    "Charon",
    "Nix",
    "Hydra",
    "Kerberos",
    "Styx",
    "Pluto",
    "EM-L1",
    "EM-L2",
    "EM-L4",
    "EM-L5",
    "Mariner 2 (spacecraft)",
    "Mars Orbiter Mission (spacecraft)",
    "Planet-C (spacecraft)",
    "Pioneer 6 (spacecraft)",
    "Wind (spacecraft)",
    "ESCAPADE-Blue (spacecraft)",
    "ESCAPADE-Gold (spacecraft)",
    "LADEE (spacecraft)",
    "LCROSS Shepherd (spacecraft)",
    "LCROSS Centaur Impactor (spacecraft",
    "Pioneer 8 (spacecraft)",
    "SOHO (spacecraft)",
    "Pioneer 10 (spacecraft)",
    "Pioneer 11 (spacecraft)",
    "Lunar Prospector (LP) (spacecraft)",
    "JUICE (spacecraft)",
    "Stardust (bus) (spacecraft)",
    "Stardust (SRC) (spacecraft)",
    "Deep Space 1 (spacecraft)",
    "Voyager 1 (spacecraft)",
    "Voyager 2 (spacecraft)",
    "NEOS (spacecraft)",
    "Hayabusa 2 (spacecraft)",
    "Ouna (spacecraft)",
    "Clementine (spacecraft)",
    "Mars Express (spacecraft)",
    "IMAP (spacecraft)",
    "Genesis (bus) (spacecraft)",
    "Hubble Space Telescope (spacecraft)",
    "Lucy (spacecraft)",
    "Genesis (SRC) (spacecraft)",
    "Mars Odyssey (spacecraft)",
    "Mars Pathfinder (spacecraft)",
    "Ulysses (spacecraft)",
    "Juno (spacecraft)",
    "EMM (spacecraft)",
    "OSIRIS-REx (spacecraft)",
    "MarCO-A (spacecraft)",
    "MarCO-B (spacecraft)",
    "Deep Impact IMPACTOR (spacecraft)",
    "Mars Reconnaissance Orbiter (spacec",
    "OMOTENASHI (spacecraft)",
    "Mars Science Laboratory (spacecraft",
    "MRO Centaur Stage (spacecraft)",
    "Galileo (spacecraft)",
    "DSCOVR (spacecraft)",
    "Spitzer Space Telescope (spacecraft",
    "Cassini (spacecraft)",
    "Phoenix (spacecraft)",
    "LRO (spacecraft)",
    "Chandrayaan-1 (spacecraft)",
    "Hera (spacecraft)",
    "ACE (spacecraft)",
    "NEAR Shoemaker (spacecraft)",
    "TESS (spacecraft)",
    "Parker Solar Probe (spacecraft)",
    "New Horizons (spacecraft)",
    "EQUULEUS (spacecraft)",
    "ICE (spacecraft)",
    "BepiColombo (Spacecraft)",
    "ICPS (Spacecraft)",
    "Hayabusa (spacecraft)",
    "DART (spacecraft)",
    "Deep Impact Flyby - EPOXI (spacecra",
    "ExoMars16 TGO (spacecraft)",
    "Solar Orbiter (spacecraft)",
    "Cassini Huygens (spacecraft)",
    "Chandra Observatory (spacecraft)",
    "Chandrayaan-2 (ORBITER) (spacecraft",
    "Chandrayaan-2 (LANDER) (spacecraft)",
    "Danuri (spacecraft)",
    "Aditya-L1",
    "Chandrayaan-3 (LANDER spacecraft)",
    "Europa Clipper (spacecraft)",
    "WISE (spacecraft)",
    "Lunar Flashlight (spacecraft)",
    "WMAP (spacecraft)",
    "Mars2020 (spacecraft)",
    "Chandrayaan-3P (ORBITER) (spacecraf",
    "James Webb Space Telescope (spacecr",
    "GRAIL-SS Second Stage (spacecraft)",
    "GRAIL-A (spacecraft)",
    "Nozomi (spacecraft)",
    "GRAIL-B (spacecraft)",
    "NEA Scout (spacecraft)",
    "InSight (spacecraft)",
    "THEMIS-B (spacecraft)",
    "THEMIS-C (spacecraft)",
    "INTEGRAL (spacecraft)",
    "MAVEN (spacecraft)",
    "Dawn (spacecraft)",
    "CONTOUR-A (SPACECRAFT FRAGMENT)",
    "CONTOUR-B (SPACECRAFT FRAGMENT)",
    "CONTOUR-C (SPACECRAFT FRAGMENT)",
    "LICIACube (spacecraft)",
    "Roman Space Telescope (spacecraft)",
    "Rosetta (spacecraft)",
    "Kepler (spacecraft)",
    "STEREO-A (spacecraft)",
    "STEREO-B (spacecraft)",
    "STEREO Third Stage (spacecraft)",
    "MESSENGER (spacecraft)",
    "SLIM (spacecraft)",
    "Lunar Trailblazer (spacecraft)",
    "Venus Express (spacecraft)",
    "Opportunity (spacecraft)",
    "Spirit (spacecraft)",
    "Psyche (spacecraft)",
    "Galileo Probe (spacecraft)",
    "Herschel Space Observatory (spacecr",
    "Planck Space Observatory (spacecraf",
    "Lucy Centaur RB Booster (spacecraft",
    "Spektr-R Observatory (spacecraft)",
    "Juno Centaur Stage (spacecraft)",
    "Infrared Space Observatory (spacecr",
    "Euclid (spacecraft)",
    "MSL Centaur Stage (spacecraft)",
    "NEOCP 6Q0B44E",
    "NEOCP J002E3",
    "Artemis I (spacecraft)",
    "CAPSTONE (spacecraft)",
    "Clementine Extended (spacecraft)",
    "OSIRIS-REx SRC (spacecraft)",
    "BioSentinel (spacecraft)",
    "Chang'e_5-T1_booster (spacecraft)",
    "ETS-6 (spacecraft)",
    "2015 PDC (simulation)",
    "Apollo 8 S-IVB (spacecraft)",
    "Apollo 9 S-IVB (spacecraft)",
    "Apollo 10 S-IVB (spacecraft)",
    "Apollo 10 LM (spacecraft)",
    "Apollo 11 S-IVB (spacecraft)",
    "Apollo 12 S-IVB (spacecraft)",
    "Vela-2A (spacecraft)",
    "LCS-1 (spacecraft)",
    "Titan-3C RB (spacecraft)",
    "IMP-7 (spacecraft)",
    "Atlas-Agena_RB (spacecraft)",
    "GOES-1 (spacecraft)",
    "LAGEOS-1 (spacecraft)",
    "FLTSATCOM 2 (spacecraft)",
    "SBS-1 (spacecraft)",
    "GOES-5 (spacecraft)",
    "WESTAR-5 (spacecraft)",
    "SATCOM-C5 (spacecraft)",
    "ASTRON (spacecraft)",
    "GOES-6 (spacecraft)",
    "AUSSAT-1 (spacecraft)",
    "AUSSAT-2 (spacecraft)",
    "COSMOS 1704 RB (spacecraft)",
    "Mir (spacecraft)",
    "AJISAI (spacecraft)",
    "TDRS-3 (spacecraft)",
    "Etalon-1 (spacecraft)",
    "Etalon-2 (spacecraft)",
    "NAVSTAR-18 (spacecraft)",
    "AUSSAT-B1 (spacecraft)",
    "LAGEOS-2 (spacecraft)",
    "Solidaridad-1 (spacecraft)",
    "Telstar-401 (spacecraft)",
    "GOES-8 (spacecraft)",
    "AUSSAT-B3 (spacecraft)",
    "AMSC-1 (spacecraft)",
    "GOES-9 (spacecraft)",
    "Echostar-1 (spacecraft)",
    "MSAT-1 (spacecraft)",
    "Echostar-2 (spacecraft)",
    "HALCA (spacecraft)",
    "GOES-10 (spacecraft)",
    "HGS-1 (spacecraft)",
    "International Space Station (spacec",
    "QuikSCAT (spacecraft)",
    "XMM-Newton (spacecraft)",
    "TERRA (spacecraft)",
    "GOES-11 (spacecraft)",
    "Echostar-6 (spacecraft)",
    "NAVSTAR-48 (spacecraft)",
    "EO-1 (spacecraft)",
    "AMC-8 (spacecraft)",
    "Intelsat-901 (spacecraft)",
    "GOES-12 (spacecraft)",
    "GRACE-1 (spacecraft)",
    "Aqua (spacecraft)",
    "Meteosat-8 (spacecraft)",
    "GALEX (spacecraft)",
    "Aura (spacecraft)",
    "Anik-F2 (spacecraft)",
    "Swift Observatory (spacecraft)",
    "Anik-F1R (spacecraft)",
    "Galaxy-15 (spacecraft)",
    "Meteosat-9 (spacecraft)",
    "Cloudsat (spacecraft)",
    "DirecTV-9S (spacecraft)",
    "XM-4 (spacecraft)",
    "Thor-5 (spacecraft)",
    "ICO_G-1 (spacecraft)",
    "Jason-2 (spacecraft)",
    "Echostar-11 (spacecraft)",
    "Kepler Booster (Third Stage) (space",
    "GOES-14 (spacecraft)",
    "NSS-12 (spacecraft)",
    "Solar Dynamics Observatory (spacecr",
    "Echostar-14 (spacecraft)",
    "SKYTERRA-1 (spacecraft)",
    "Tiangong-1 (spacecraft)",
    "BEIDOU-M3 (spacecraft)",
    "NuSTAR (spacecraft)",
    "Echostar-17 (spacecraft)",
    "Meteosat-10 (spacecraft)",
    "NAVSTAR-67 (spacecraft)",
    "NEOSsat (spacecraft)",
    "NAVSTAR-68 (spacecraft)",
    "Chang'e_3_booster (spacecraft)",
    "Gaia (spacecraft)",
    "OCO-2 (spacecraft)",
    "Himawari-8 (spacecraft)",
    "SMAP (spacecraft)",
    "MMS-1 (spacecraft)",
    "MMS-2 (spacecraft)",
    "MMS-3 (spacecraft)",
    "MMS-4 (spacecraft)",
    "DirecTV-15 (spacecraft)",
    "Meteosat-11 (spacecraft)",
    "MEXSAT-2 Centaur RB (spacecraft)",
    "LISA Pathfinder (spacecraft)",
    "Jason-3 (spacecraft)",
    "Intelsat-33E (spacecraft)",
    "Himawari-9 (spacecraft)",
    "GOES-16 (spacecraft)",
    "SpaceX Roadster (spacecraft)",
    "GOES-17 (spacecraft)",
    "GSAT-6A (spacecraft)",
    "Chang'e_4_booster (spacecraft)",
    "GOES-18 (spacecraft)",
    "ACS3 (spacecraft)",
    "GOES-19 (spacecraft)",
    "Cert-2 Centaur RB Booster",
    "SPHEREx (spacecraft)",
    "NISAR (spacecraft)",
    "LISA Pathfinder Propulsion Module (",
    "WT1190F",
    "2017 PDC (simulation)",
    "2017 PDCa (simulation)",
    "2019 PDC (simulation)",
    "c2019 PDC (simulation)",
    "2021 PDC (simulation)",
    "2021 PDCa (simulation)",
    "2023 PDC (simulation)",
    "2023 PDCa (simulation)",
    "2023 PDCf (simulation)",
    "2024 PDC25 (simulation)",
    "2024 PDC25a (simulation)",
    "TTX19 (simulation)",
    "TTX19a (simulation)",
    "2022 TTX (simulation)",
    "2023 TTX (simulation)",
    "2023 NM (debris)",
    "Odin (spacecraft)",
    "Hartley 2",
    "Siding Spring",
    "ISON_NG1",
    "ISON_NG2",
    "Psyche (mission target)",
    "6489 Golevka (1991 JX)",
    "101955 Bennu (1999 RQ36)",
    "Arrokoth",
    "2018_AV2 (spacecraft)",
    "9O0DC57 (spacecraft)",
    "9U01FF6 (spacecraft)",
    "Tianwen-1 (spacecraft)",
    "Luna-25 STAGE (spacecraft)",
    "EscaPADE STAGE (spacecraft)",
    "Patroclus (system barycenter)",
    "Patroclus (primary body)",
    "Menoetius",
    "Quaoar (system barycenter)",
    "Quaoar (primary body)",
    "Weywot",
    "Didymos (system barycenter)",
    "Didymos (primary body)",
    "Dimorphos",
    "Orcus (system barycenter)",
    "Orcus (primary body)",
    "Vanth",
    "Salacia (system barycenter)",
    "Salacia (primary body)",
    "Actaea",
    "Haumea (system barycenter)",
    "Haumea (primary body)",
    "Hi'iaka",
    "Namaka",
    "Eris (system barycenter)",
    "Eris (primary body)",
    "Dysnomia",
    "|=Kagara (system barycenter)",
    "|=Kagara (primary body)",
    "Haunu",
    "2003 UN284 (system barycenter)",
    "2003 UN284 (primary body)",
    "2003 UN284 1",
    "1999 OJ4 (system barycenter)",
    "1999 OJ4 (primary body)",
    "1999 OJ4 1",
    "1998 WW31 (system barycenter)",
    "1998 WW31 (primary body)",
    "1998 WW31 1",
    "2001 QW322 (system barycenter)",
    "2001 QW322 (primary body)",
    "2001 QW322 1",
    "Surveyor-2 Centaur RB",
    # Small bodies
    "Ceres",
    # "Pluto",
    "Haumea",
    "Makemake",
    "Eris",
]


if __name__ == "__main__":
    a: Body = "Alfonso"
